### ISSUE TITLE
How do you put this in google sites?

### ISSUE THREAD

**Issue by BypassGoGuardianPLS** [Unzor/wasmpsx#2]
I dont code, but i understand basic html stuff, maybe you could help me?

**Comment by Unzor** [comment]
No. This is not intended for Google Sites. You will have to do it yourself using Replit. Fortunately, since you know basic HTML, I think this will be easy for you. WASMpsx plays in an element named <wasmpsx-player>, so you can download the .zip file,  unzip it in Replit, and add this code to index.html:
```html
<!DOCTYPE HTML>
<html>
<body>
    <wasmpsx-player id="my-wasmpsx-element"></wasmpsx-player>
    <script src="wasmpsx.min.js"></script>
    <script>
        document.getElementById('my-wasmpsx-element').loadUrl("PATH TO GAME FILE HERE");
    </script>
</body>
</html>
```
Just make sure to replace PATH TO GAME FILE HERE with the path of the file of the game you want to add. Also make sure it is in .bin format.
Once done, you can add this to your Google Site using an IFrame.

**Comment by BypassGoGuardianPLS** [comment]
Ok thanks. Yes this is going in an unblocked website but its only available to students at my school. I'll try this. Also, is it possible to add a load file button instead of file path? As i said, my knowledge of HTML is basic.

**Comment by BypassGoGuardianPLS** [comment]
![Screenshot 2022-03-22 20 06 03](https://user-images.githubusercontent.com/97196180/159601759-28ed39e2-c09f-40e6-bae7-eebaed1410cc.png)

This is what happens when i try to create it.

**Comment by Unzor** [comment]
I did not mean the repo, I meant this ZIP file: http://download-wasmpsx.glitch.me/, it has all the necessary files only. Then move all the files to the parent folder and rename this.html to index.html.

And answering the other question, yes, it is, using blobs.

```
  <input id="e" style="display: none;" type="file"  onchange="document.querySelector('#my-wasmpsx-element').readFile(this.files[0]);" />
```

**Comment by BypassGoGuardianPLS** [comment]
the zip file comes up empty.

**Comment by BypassGoGuardianPLS** [comment]
I did it, just took the original source of the github repo and imported it to repl. Thank you for the help.

**Comment by sDetective** [comment]
I'm new to code too I'm trying to get it on Google sites
